services:

  mysql:
    image: mysql:latest
    ports:
        - 3307:3306
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=turnerodb
        - TZ=America/Argentina/Mendoza
    networks:
      - express-app

  app:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_NAME=turnerodb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_PORT=3306
      - DATABASE_HOST=mysql
    networks:
      - express-app

networks:
  express-app: